export const permissionCatalog = [
    'manage_users',
    'manage_roles',
    'manage_listings',
    'approve_listings',
    'moderate_reports',
    'manage_payments',
    'manage_settings',
    'switch_backend',
    'view_audit_logs',
    'manage_content',
    'manage_blog',
    'manage_locations',
    'manage_amenities',
    'manage_inquiries',
    'manage_bookings',
    'export_reports',
    'manage_notifications',
    'manage_support_tickets',
    'manage_backend_health',
    'manage_property_reviews',
    'manage_featured_listings',
    'manage_plans',
    'manage_legal_content',
    'impersonate_users',
] as const

export type Permission = (typeof permissionCatalog)[number]
