import type { Permission } from "@/lib/core/rbac/permissions";

export const roleMatrix: Record<string, Permission[]> = {
  super_admin: [
    "manage_users",
    "manage_roles",
    "manage_listings",
    "approve_listings",
    "moderate_reports",
    "manage_payments",
    "manage_settings",
    "switch_backend",
    "view_audit_logs",
    "manage_content",
    "manage_blog",
    "manage_locations",
    "manage_amenities",
    "manage_inquiries",
    "manage_bookings",
    "export_reports",
    "manage_notifications",
    "manage_support_tickets",
    "manage_backend_health",
    "manage_property_reviews",
    "manage_featured_listings",
    "manage_plans",
    "manage_legal_content",
    "impersonate_users",
  ],
  admin: [
    "manage_users",
    "manage_listings",
    "approve_listings",
    "moderate_reports",
    "manage_settings",
    "view_audit_logs",
    "manage_content",
    "manage_blog",
    "manage_locations",
    "manage_amenities",
    "manage_inquiries",
    "manage_bookings",
    "export_reports",
    "manage_notifications",
    "manage_support_tickets",
    "manage_backend_health",
    "manage_property_reviews",
    "manage_featured_listings",
    "manage_plans",
    "manage_legal_content",
  ],
  moderator: [
    "manage_listings",
    "approve_listings",
    "moderate_reports",
    "manage_inquiries",
    "manage_bookings",
    "manage_property_reviews",
  ],
  support: [
    "manage_inquiries",
    "manage_bookings",
    "manage_notifications",
    "manage_support_tickets",
  ],
  landlord: ["manage_listings", "manage_inquiries", "manage_bookings"],
  agent: ["manage_listings", "manage_inquiries", "manage_bookings"],
  tenant: [],
  viewer: [],
  property_manager: ["manage_listings", "manage_inquiries", "manage_bookings"],
  accountant: ["manage_payments", "export_reports", "manage_plans"],
};
